name: Publish Staging

on:
  push:
    branches:
      - staging

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      deployments: write

    strategy:
      matrix:
        include:
          - projectName: "portal-staging"

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3

      - name: Setup node env 🏗
        uses: actions/setup-node@v3
        with:
          node-version: lts/gallium
          cache: "yarn"

      - name: Install dependencies 👨🏻‍💻
        run: yarn

      - name: Run build
        run: yarn portal:build

      - name: Publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_PRODUCTION_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_PRODUCTION_ACCOUNT_ID }}
          directory: ./apps/portal/dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
